/**
 * One Gramlot page in the browser.
 *
 * @module
 */
import type {DomElement, DomDocument, DomNode} from './dom.d.ts';
import type {Bag} from '@genrojs/bag';
import type {SourceBag, SourceBagNode} from '@genrojs/builders';
import type {GramlotBuilder} from './builder/gramlot-builder.js';
import type {GramlotRenderer} from './renderer/gramlot-renderer.js';
import type {InOut} from './inout.js';
import type {SourceReference} from './references.js';
import type {MainTransport} from './transport.js';

/** The options of a `Gramlot` instance. */
export interface GramlotOptions {
    /** The id of the server page, as registered by the host. */
    pageId?: string;
    /** The URL of the `main` Source endpoint. */
    mainUrl?: string;
    /** The URL of the remote Source endpoint. */
    sourceUrl?: string;
    /** The URL of the page close endpoint. */
    closeUrl?: string;
    /** The id of the root element that receives the page. */
    rootId?: string;
    /** The root element; when null it is looked up by `rootId`. */
    element?: DomElement | null;
    /** The document of the page. */
    document?: DomDocument;
    /** A transport, or `false` for an instance with no server transport. */
    transport?: MainTransport | false | null;
    /** Grammar collections loaded into the builder. */
    collections?: unknown[];
}

/** The lifecycle state of a `Gramlot` instance. */
export type GramlotState = 'ready' | 'loading' | 'started' | 'failed' | 'disposed';

/**
 * One Gramlot page. The Data root is the builder's, the binding runtime subscribes to it before
 * the renderer observes the Source.
 */
export class Gramlot {
    /** The id of the server page. */
    pageId: string | undefined;
    /** The registry of the Logic classes of the page. */
    logicRegistry: unknown;
    /** The builder that owns the Source and the Data. */
    builder: GramlotBuilder;
    /** The binding runtime of the page. */
    binding: unknown;
    /** The Data Bag of the page. */
    data: Bag;
    /** The `gramlot.inout` object: send, receive, save and download Data branches. */
    inout: InOut;
    /** The Source Bag observed by the renderer. */
    source: SourceBag;
    /** The live renderer of the page. */
    renderer: GramlotRenderer;
    /** The server transport, or null. */
    transport: MainTransport | null;
    /** The remote Source requests in progress, by target node. */
    remoteRequests: Map<SourceBagNode, {controller: AbortController}>;
    /** The lifecycle state. */
    state: GramlotState;
    /** The controller aborted on dispose. */
    abort: AbortController;
    /** The pending `start` promise, while loading. */
    loading?: Promise<Gramlot> | null;
    /** Create the page instance; the construction order is the one of the source plan. */
    constructor(options?: GramlotOptions);
    /** Load `main` from the server and mount it; resolves with the instance. */
    start(): Promise<Gramlot>;
    /** Request `main` from the transport and mount it. */
    loadMain(): Promise<Gramlot>;
    /** Start from an embedded typed Source, with the same observed insertion as `main`. */
    startSource(wire: SourceBag | string): Gramlot;
    /** Validate and insert `main` in the Source. */
    mountMainSource(wire: SourceBag | string): Gramlot;
    /**
     * A Source from a SourceBag or a TYTX wire; only Gramlot Source Bags are accepted, before any
     * effect. The received Source activates its inline code.
     */
    prepareSource(wire: SourceBag | string, builder?: GramlotBuilder): SourceBag;
    /**
     * Replace the children of one Source node with a remote Source, only after the incoming Source
     * validates. Resolves with true when applied, false when superseded or cancelled.
     */
    remoteSource(target: SourceBagNode, method: string, params?: Record<string, unknown>): Promise<boolean>;
    /** Resolve a node or DOM reference descriptor. */
    reference(descriptor: SourceReference): SourceBagNode | DomElement;
    /** The Source node of the nearest element generated by the renderer. */
    getBaseSourceNode(domNode: DomNode): SourceBagNode | null;
    /** The element built from a Source node, or null. */
    getDomNode(sourceNode: SourceBagNode): DomElement | null;
    /** Dispose the page: abort requests, close bindings and the renderer, and close the server page. */
    dispose(options?: {beacon?: boolean}): void;
}
