/**
 * The DOM of one Gramlot page and its correspondence with the Source (`gramlot.dom`).
 *
 * @module
 */
import type {SourceBagNode} from '@genrojs/builders';
import type {DomElement, DomNode} from '../dom.d.ts';
import type {SourceReference} from '../references.js';
import {Handler} from './handler.js';

/** The DOM and its correspondence with the Source. */
export class DomHandler extends Handler {
    /** Resolve a node or DOM reference descriptor. */
    reference(descriptor: SourceReference): SourceBagNode | DomElement;
    /** The Source node of the nearest element generated by the renderer. */
    getBaseSourceNode(domNode: DomNode): SourceBagNode | null;
    /** The element built from a Source node, or null. */
    getDomNode(sourceNode: SourceBagNode): DomElement | null;
}
