/* @ts-self-types="./dom-handler.d.ts" */
/**
 * The DOM of one Gramlot page and its correspondence with the Source (`gramlot.dom`).
 *
 * @module
 */
import {Handler} from './handler.js';

/** The DOM and its correspondence with the Source. */
export class DomHandler extends Handler {
    reference(descriptor) { return this.gramlot.src.renderer.references.resolve(descriptor); }
    /** The Source node of the nearest element generated by the renderer (§4.11bis). */
    getBaseSourceNode(domNode) { return this.gramlot.src.renderer.getBaseSourceNode(domNode); }
    /** The element built from a Source node, or null (§4.11bis). */
    getDomNode(sourceNode) { return this.gramlot.src.renderer.getDomNode(sourceNode); }
}
