/**
 * The live renderer of a Gramlot page.
 *
 * @module
 */
import type {DomElement, DomNode, DomDocument, DomFragment} from '../dom.d.ts';
import type {SourceBag, SourceBagNode} from '@genrojs/builders';
import type {GramlotBuilder} from '../builder/gramlot-builder.js';
import type {References} from '../references.js';
import {GramlotHtmlRenderer} from './gramlot-html-renderer.js';

/**
 * Own the live DOM lifecycle driven by typed Source insert, update and delete events.
 * The attribute rules are `GramlotHtmlRenderer`'s; this class replaces its output with DOM elements.
 */
export class GramlotRenderer extends GramlotHtmlRenderer {
    /** The renderer output type: DOM objects. */
    static renderType: string;
    /** The observed Source. */
    source: SourceBag;
    /** The element that receives the rendered page. */
    destination: DomElement;
    /** The table of the references of the Source. */
    references: References;
    /** True after `dispose`. */
    disposed: boolean;
    /** The id of this renderer instance, which scopes generated radio names. */
    instanceId: string;
    /** Create the live renderer of one page; `binding` is the binding runtime of the page. */
    constructor(builder: GramlotBuilder, source: SourceBag, destination: DomElement, options?: {binding?: unknown});
    /** The binding runtime of the page. */
    get binding(): unknown;
    /** The inline compiler of the page: the live renderer evaluates the `==` expressions. */
    get inlineCompiler(): unknown;
    /** The resolved projection of a node: runtime values, then the `==` expressions. */
    evaluateExpressions(node: SourceBagNode, runtimeAttrs: Record<string, unknown>): Record<string, unknown>;
    /** Render a node, or a structural Source fragment, to DOM; a data-element renders nothing. */
    render(node: SourceBagNode, opts?: Record<string, unknown>): DomNode | null;
    /** Render a structural Source fragment to a DOM fragment. */
    renderFragment(node: SourceBagNode, opts?: Record<string, unknown>): DomFragment;
    /** Create one detached element for a node (a DOM element; typed `any` because it replaces the string output of the base class). */
    // deno-lint-ignore no-explicit-any
    renderedItem(node: SourceBagNode, item: unknown, runtimeAttrs: Record<string, unknown>,
        opts?: {tag?: string; document?: DomDocument}): any;
    /** Validate a detached candidate Source without changing the observed Source. */
    validateCandidate(block: SourceBag, options?: {replacingNode?: SourceBagNode | null}): void;
    /** Suspend rendering for a mounted branch; the Source keeps changing normally. */
    freeze(node: SourceBagNode): void;
    /** Resume the whole branch and build its current Source once. */
    unfreeze(node: SourceBagNode): void;
    /** Source event intake: queue the event and process the queue in arrival order. */
    receive(event: {evt: string; node: SourceBagNode; [key: string]: unknown}): void;
    /** Whether a node still belongs to the observed Source. */
    attached(node: SourceBagNode): boolean;
    /** Build an inserted node and report the build to the binding runtime. */
    insert(node: SourceBagNode): void;
    /** Build the DOM of a node inside `container`, before `before`. */
    buildNode(node: SourceBagNode, container: DomNode, before?: DomNode | null, parent?: unknown): void;
    /** Set the container of a render record and of its children. */
    assignContainer(record: unknown, container: DomNode): void;
    /** Apply a Source update event to the DOM of a node. */
    update(node: SourceBagNode, event: string): void;
    /** Project the resolved attributes and value of a node on its DOM elements. */
    project(node: SourceBagNode, change?: unknown): void;
    /** The element built from a Source node, or null. */
    getDomNode(sourceNode: SourceBagNode): DomElement | null;
    /** The Source node of the nearest element generated by this renderer, climbing from `domNode`, or null. */
    getBaseSourceNode(domNode: DomNode): SourceBagNode | null;
    /** Register a cleanup callback run when the DOM of a node is removed; returns the function that unregisters it. */
    onDispose(node: SourceBagNode, callback: () => void): () => void;
    /** Remove the DOM of a node and run its cleanup callbacks. */
    remove(node: SourceBagNode): void;
    /** Stop observing the Source and remove all rendered DOM. */
    dispose(): void;
}
